language: r
os: linux
dist: trusty

addons:
  apt:
    packages:
    - libproj-dev
    - libgdal-dev

r_github_packages:
  - jimhester/lintr
  - jimhester/covr
  - r-lib/pkgdown
  - ropensci/hddtools

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  strategy: git
  token: $GITHUB_PAT
  keep_history: true
  on:
    branch: master
